apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../app/
images:
- name: registry-1.docker.io/egrol/spring-boot-log4j-vulnerable:0.1
  newName: image-registry.openshift-image-registry.svc:5000/cicd/spring-boot-log4j-vulnerable
  newTag: b0669c7c60489fa46935abed12a727bbd11c93768b8a222d59b100c7c96b04c3
